In [16]:
import tensorflow as tf
import numpy as np
import sys
# sys.path.insert(0, 'utils/')

from utils.seq_sampler import DataLoader
from utils.data import Vocab

In [25]:
mb = 2
train_fname = "ptb_char/trainX.txt"
train_data = DataLoader(train_fname, mb)
vocab = Vocab("ptb_char/vocab.txt")

---------------------------------------------------------------
  Dataset:  ptb_char/trainX.txt
  Len(xdata) =  42068
  Max_seq_len =  518
---------------------------------------------------------------


In [26]:
imax = -1
i = 0
for x_seq in train_data:
    mk = tf.cast(tf.greater_equal(x_seq, 0), dtype=tf.float32)
    for t in range(x_seq.shape[1]):
        i_t = np.expand_dims(x_seq[:,t], axis=1)
        m_t = tf.expand_dims(mk[:,t],axis=1)
        # print(i_t)
        # print(m_t)
        x_t = tf.squeeze( tf.one_hot(i_t,depth=vocab.size) )
        print("i_t")
        print(i_t)
        print("x_t")
        print(x_t)
        if i_t.shape[0] == 1:
            x_t = tf.expand_dims(x_t, axis=0)
        # print(x_t.shape)
        # print(x_t[1])
    # print(x_seq[0])
    i += 1
    if i > imax:
        break

ptrs: 42067
i_t
[[30]
 [25]]
x_t
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]], shape=(2, 49), dtype=float32)
i_t
[[37]
 [26]]
x_t
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]], shape=(2, 49), dtype=float32)
i_t
[[22]
 [43]]
x_t
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.