In [5]:
import tensorflow as tf
import numpy as np



In [24]:
x = tf.constant([[1.,0.,1.,0.]])

smth = tf.constant([[-1., 0.]])

corr = tf.constant([[1., 1.]])

w = tf.matmul(x, smth, transpose_a=True)

pred = tf.matmul(x, w)

err = tf.subtract(corr, pred)
print(corr)
print(pred)
print(err)

for _ in range(20):

    dW = tf.matmul(x, err,  transpose_a=True) * 0.1
    w = tf.add(w, dW)
    print()

    pred = tf.matmul(x, w)
    err = tf.subtract(corr, pred)
    print(corr)
    print(pred)
    print(err)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[-2.  0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[3. 1.]], shape=(1, 2), dtype=float32)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[-1.4  0.2]], shape=(1, 2), dtype=float32)
tf.Tensor([[-2.4 -0.8]], shape=(1, 2), dtype=float32)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[-1.88        0.03999999]], shape=(1, 2), dtype=float32)
tf.Tensor([[-2.88       -0.96000004]], shape=(1, 2), dtype=float32)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[-2.456      -0.15200002]], shape=(1, 2), dtype=float32)
tf.Tensor([[-3.456     -1.1520001]], shape=(1, 2), dtype=float32)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[-3.1472     -0.38240004]], shape=(1, 2), dtype=float32)
tf.Tensor([[-4.1472 -1.3824]], shape=(1, 2), dtype=float32)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[-3.9766402  -0.65888005]], shape=(1, 2), dtype=float32)
tf.Tensor([[-4.9766